// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPwX9upDp-flkmNsCavMonifBQluastBQ',
    appId: '1:826917239714:web:34136d38b90440492ed0fb',
    messagingSenderId: '826917239714',
    projectId: 'proyecto-final-6b20e',
    authDomain: 'proyecto-final-6b20e.firebaseapp.com',
    storageBucket: 'proyecto-final-6b20e.firebasestorage.app',
    measurementId: 'G-6JX1NVSMMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfOKggQasLN33OGe8URF511vwPNYKP3k8',
    appId: '1:826917239714:android:b6b9d382a24e0fad2ed0fb',
    messagingSenderId: '826917239714',
    projectId: 'proyecto-final-6b20e',
    storageBucket: 'proyecto-final-6b20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD9CdfVoCVv2v1HWCAa471Ka857gi3dkw',
    appId: '1:826917239714:ios:3bd4eb5c89355a752ed0fb',
    messagingSenderId: '826917239714',
    projectId: 'proyecto-final-6b20e',
    storageBucket: 'proyecto-final-6b20e.firebasestorage.app',
    iosClientId: '826917239714-m1e39pa51j51ia8tr95ol9dqa6gcjg4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.inicioSesion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD9CdfVoCVv2v1HWCAa471Ka857gi3dkw',
    appId: '1:826917239714:ios:3bd4eb5c89355a752ed0fb',
    messagingSenderId: '826917239714',
    projectId: 'proyecto-final-6b20e',
    storageBucket: 'proyecto-final-6b20e.firebasestorage.app',
    iosClientId: '826917239714-m1e39pa51j51ia8tr95ol9dqa6gcjg4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.inicioSesion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPwX9upDp-flkmNsCavMonifBQluastBQ',
    appId: '1:826917239714:web:8b541442c2207d752ed0fb',
    messagingSenderId: '826917239714',
    projectId: 'proyecto-final-6b20e',
    authDomain: 'proyecto-final-6b20e.firebaseapp.com',
    storageBucket: 'proyecto-final-6b20e.firebasestorage.app',
    measurementId: 'G-R1ZGMYP3CV',
  );

}